### PR TITLE
Fix block method return filepath and lineno using call stack frame.

### LINKED ISSUE #39: Methods defined via blocks produce incorrect call-locations
### Introduction

As identified in https://github.com/Shopify/rotoscope/pull/38.

When using dynamically defined methods via `define_method` and `define_singleton_method`, the call stack is inconsistent compared with how predefined Ruby methods look.

Failing test here: https://github.com/Shopify/rotoscope/blob/5155f3912288740dc804cfa0a06d09f9fc81c20b/test/rotoscope_test.rb#L413-L428

### Problem

On `:call` events, the frame points to where the method is received in Ruby, i.e. the block passed to `define_method` or `define_singleton_method`. This is the [expected behaviour](https://github.com/Shopify/rotoscope/issues/16) for Ruby invocations:

> [TracePoint] has the unfortunate side effect of pointing to the callee of the method (i.e. where the method is received), rather than the caller.

_But_, when the `:return` event fires, instead of pointing to the end of the method definition like a normal ruby method, it points one frame up the stack, to where the original `caller` occurred. Since we assume Ruby methods point one level deeper, Rotoscope pops the frame one level further, and points to where the caller's caller came from. This means the `call` and `return` events won't match up.

### Solution?

I tried to figure out how to get around this one (by using Ruby's bitmasks to determine if it was a dynamically defined method, etc.), but I've been unsuccessful thus far.

This problem is currently avoidable via `flatten: true`, since [unmatched returns are ignored](https://github.com/Shopify/rotoscope/blob/929d7e27c87c740a864f857741272cadce584513/ext/rotoscope/rotoscope.c#L161).

### PR DESCRIPTION
**Pull request by dylanahsmith**
Fixes #39
Closes #43

The issue described in #39 with getting the correct filepath and lineno for block methods is only a problem on the return event.  Instead of trying to detect this case, we can avoid it completely by just using the filepath and lineno that we got for the call event on the return event by getting it from the rotoscope stack.

Since the filepath is used for filtering, we now need to include filtered calls on the rotoscope stack, using a blacklisted flag to allow them to be skipped over for logging the non-blacklisted caller.

I used the tests from #43 in this PR.

- [x] `bin/fmt` was successfully run

### CODE REVIEW

File: ext/rotoscope/rotoscope.c [hunk 1]
```diff
@@ -133,30 +133,24 @@ static rs_tracepoint_t extract_full_tracevals(rb_trace_arg_t *trace_arg,
...
-  } else if (event & EVENT_RETURN) {
-    if (tracecmp(&trace, &rs_stack_peek(stack)->tp)) rs_stack_pop(stack);
+unsigned char output_buffer[LOG_BUFFER_SIZE];
+static void log_trace_event_with_caller(FILE *stream,
+                                        rs_stack_frame_t *stack_frame,
+                                        rs_strmemo_t **call_memo) {
+  rs_stack_frame_t *caller = stack_frame->caller;
+  while (caller->blacklisted) {
+    caller = caller->caller;
+  }
```
Comment (jahfer) [inline ext/rotoscope/rotoscope.c]: From discussions I've had (cc @stephenminded @airhorns), it sounds like we actually want to print the _true_ caller, even if they are blacklisted; we just want to avoid writing calls into the blacklisted areas. 

Should we make this a config option?

File: ext/rotoscope/rotoscope.c [hunk 2]
```diff
@@ -171,19 +165,40 @@ static void event_hook(VALUE tpval, void *data) {
...
 
-  if (rejected_path(trace_path.filepath, config)) return;
+  rs_callsite_t trace_path;
+  bool blacklisted;
+  if (event_flag & EVENT_CALL) {
+    trace_path = tracearg_path(trace_arg);
+    blacklisted = rejected_path(trace_path.filepath, config);
+  } else {
+    if (rs_stack_empty(&config->stack)) return;
+    rs_stack_frame_t *call_frame = rs_stack_peek(&config->stack);
```
Comment (jahfer) [inline ext/rotoscope/rotoscope.c]: 💡 such a great idea 💯 🎉

File: ext/rotoscope/rotoscope.c (hunk 1 above)
Comment (stephenminded) [reply ext/rotoscope/rotoscope.c]: A very common case will be calls from tests, aka a blacklisted context. So, for instance:
```
test "whatever" do
   order.do_a_thing
end

class Order
  def do_a_thing
    do_some_other_thing
  end
end
```

Right now, for wedge:
  - I don't care what test called `order.do_a_thing` 
  - I care that `order.do_a_thing` called `some_other_thing`

Potentially we can argue that I do care if the test that called `order.do_a_thing` is in a different component. In that case, having a config option to write what blacklisted context called into a non-blacklisted context (`test "whatever"` in the above example) would be a good idea.

File: ext/rotoscope/rotoscope.c [hunk 3]
```diff
@@ -133,30 +133,24 @@ static rs_tracepoint_t extract_full_tracevals(rb_trace_arg_t *trace_arg,
...
+unsigned char output_buffer[LOG_BUFFER_SIZE];
+static void log_trace_event_with_caller(FILE *stream,
+                                        rs_stack_frame_t *stack_frame,
+                                        rs_strmemo_t **call_memo) {
+  rs_stack_frame_t *caller = stack_frame->caller;
+  while (caller->blacklisted) {
+    caller = caller->caller;
+  }
+
+  sprintf((char *)output_buffer, RS_FLATTENED_CSV_FORMAT "\n",
```
Comment (stephenminded) [inline ext/rotoscope/rotoscope.c]: `snprintf` to limit to the buffer size?

File: ext/rotoscope/rotoscope.c [hunk 4]
```diff
@@ -133,30 +133,24 @@ static rs_tracepoint_t extract_full_tracevals(rb_trace_arg_t *trace_arg,
...
-    }
-  } else if (event & EVENT_RETURN) {
-    if (tracecmp(&trace, &rs_stack_peek(stack)->tp)) rs_stack_pop(stack);
+unsigned char output_buffer[LOG_BUFFER_SIZE];
+static void log_trace_event_with_caller(FILE *stream,
+                                        rs_stack_frame_t *stack_frame,
+                                        rs_strmemo_t **call_memo) {
+  rs_stack_frame_t *caller = stack_frame->caller;
+  while (caller->blacklisted) {
+    caller = caller->caller;
```
Comment (stephenminded) [inline ext/rotoscope/rotoscope.c]: Any chance of walking all the way back up the stack to where `caller->caller` is null?

File: ext/rotoscope/rotoscope.c (hunk 1 above)
Comment (dylanahsmith) [reply ext/rotoscope/rotoscope.c]: Sure, we could easily change it to return the `true` caller.  I think that should be done in another PR though.  It would probably require a bunch of test changes if we just change the default behaviour.  I'm not sure if we want maintain a config option if we only care about the new way for the blacklist to work.

File: ext/rotoscope/rotoscope.c (hunk 4 above)
Comment (dylanahsmith) [reply ext/rotoscope/rotoscope.c]: The stack inserts a root node in `insert_root_node` and this PR makes it not blacklisted so we wouldn't have to worry about dereferencing NULL.

File: ext/rotoscope/rotoscope.c (hunk 3 above)
Comment (dylanahsmith) [reply ext/rotoscope/rotoscope.c]: Looks like that was a change in #43 that I missed.  Just pushed a commit to do that here.
